language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.2
  - 5.3
  - 5.6
  - 7
  
after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/indieweb-post-kinds/
    - GH_REF: https://github.com/dshanske/indieweb-post-kinds.git
    - secure: <your key>


matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1  WP_PULUGIN_DEPLOY=1

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    elif [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - bash bin/install-wp-tests.sh wordpress root '' localhost $WP_VERSION

script: phpunit
